### ISSUE TITLE
[Enhancement] Option to Save Specific Pictures

### ISSUE THREAD

**Issue by LumiWasTaken** [leszekhanusz/diffusion-ui#65]
Suggestion:
The Hamburger menu is a little lonely, what about adding a little Button below "Generate Again" to save the image?

_Preferably without any Watermarks or Exif data... filenames ofc can be something like seed+modelhash_

**Comment by leszekhanusz** [comment]
Done in #68

**Comment by leszekhanusz** [comment]
Note that a feature I would like to make in the future is to store EVERYTHING which was done to generate the image in the image metadata. So that you would be able to take an image you made a month ago and if you upload it to diffusion-ui it would detect it and ask you if you want to regenerate it again.
This could be configurable of course.

**Comment by LumiWasTaken** [comment]
> Note that a feature I would like to make in the future is to store EVERYTHING which was done to generate the image in the image metadata. So that you would be able to take an image you made a month ago and if you upload it to diffusion-ui it would detect it and ask you if you want to regenerate it again.

It makes sense and stuff, i just sometimes dont like sharing my prompt for example because there are a few "nice people" who had the audacity to just straight up copy me and claim its their work cuz i forgot that i had the data added in the settings.

Thats why i like downloading the pics / saving them and having their name be modelhash-seed Prompt_Token1 Prompt_Token2 since i dont really need the negative prompt
